@echo off
REM Fover Backend - Database Migration Helper (Windows)
REM Usage: migrate.bat <command> [arguments]

setlocal enabledelayedexpansion

REM Color codes for Windows (using ANSI if Windows 10+)
set GREEN=[92m
set YELLOW=[93m
set RED=[91m
set BLUE=[94m
set NC=[0m

REM Check if running from project root
if not exist "alembic" (
    echo Error: alembic folder not found. Run this from the project root directory.
    exit /b 1
)

REM Load .env if it exists
if exist ".env" (
    for /f "delims== tokens=1,2" %%A in (.env) do (
        if not "%%A"=="" if not "%%A:~0,1%"=="#" (
            set "%%A=%%B"
        )
    )
)

REM Check DATABASE_URL
if "!DATABASE_URL!"=="" (
    echo %RED%Error: DATABASE_URL not set%NC%
    echo Set it with: set DATABASE_URL=postgresql://user:pass@host:5432/db
    exit /b 1
)

REM Process commands
if "%1"=="" (
    call :show_help
    exit /b 0
)

if "%1"=="help" (
    call :show_help
    exit /b 0
)

if "%1"=="status" (
    call :migrate_status
    exit /b !errorlevel!
)

if "%1"=="current" (
    call :migrate_current
    exit /b !errorlevel!
)

if "%1"=="history" (
    call :migrate_history
    exit /b !errorlevel!
)

if "%1"=="generate" (
    if "%2"=="" (
        set "message=update schema"
    ) else (
        set "message=%2"
    )
    call :migrate_generate "!message!"
    exit /b !errorlevel!
)

if "%1"=="create" (
    if "%2"=="" (
        set "message=manual migration"
    ) else (
        set "message=%2"
    )
    call :migrate_create "!message!"
    exit /b !errorlevel!
)

if "%1"=="upgrade-head" (
    call :migrate_upgrade_head
    exit /b !errorlevel!
)

if "%1"=="upgrade-one" (
    call :migrate_upgrade_one
    exit /b !errorlevel!
)

if "%1"=="downgrade-one" (
    call :migrate_downgrade_one
    exit /b !errorlevel!
)

if "%1"=="downgrade-all" (
    call :migrate_downgrade_all
    exit /b !errorlevel!
)

if "%1"=="test" (
    call :migrate_test
    exit /b !errorlevel!
)

if "%1"=="backup" (
    call :migrate_backup
    exit /b !errorlevel!
)

if "%1"=="check-prod" (
    call :migrate_check_prod
    exit /b !errorlevel!
)

if "%1"=="health-check" (
    call :migrate_health_check
    exit /b !errorlevel!
)

echo Unknown command: %1
call :show_help
exit /b 1

REM ============================================================================
REM Function Definitions
REM ============================================================================

:show_help
echo.
echo ┌─────────────────────────────────────────────┐
echo ^| Fover Backend Migration Helper ^(Windows^)   ^|
echo └─────────────────────────────────────────────┘
echo.
echo USAGE: migrate.bat ^<command^> [arguments]
echo.
echo DEVELOPMENT COMMANDS:
echo   migrate.bat status            - Show current migration version
echo   migrate.bat history           - Show migration history
echo   migrate.bat current           - Show current version only
echo   migrate.bat generate "msg"    - Generate autogenerated migration
echo   migrate.bat create "msg"      - Create empty migration
echo   migrate.bat upgrade-head      - Apply all pending migrations
echo   migrate.bat upgrade-one       - Apply one pending migration
echo   migrate.bat downgrade-one     - Rollback one migration
echo   migrate.bat downgrade-all     - Rollback all migrations
echo   migrate.bat test              - Test migrations ^(no changes^)
echo.
echo PRODUCTION COMMANDS:
echo   migrate.bat backup            - Backup database
echo   migrate.bat check-prod        - Check production migrations
echo   migrate.bat health-check      - Check database connection
echo.
echo EXAMPLES:
echo   migrate.bat generate "add email verification"
echo   migrate.bat status
echo   migrate.bat backup
echo   migrate.bat upgrade-head
echo.
exit /b 0

:migrate_status
echo.
echo %BLUE%Migration Status%NC%
echo ─────────────────────────────────────────
alembic current
echo ─────────────────────────────────────────
echo %YELLOW%Latest available:%NC%
alembic heads
echo.
exit /b !errorlevel!

:migrate_current
alembic current
exit /b !errorlevel!

:migrate_history
echo.
echo %BLUE%Migration History%NC%
alembic history --verbose
echo.
exit /b !errorlevel!

:migrate_generate
echo.
echo %BLUE%Generating migration: '%~1'%NC%
alembic revision --autogenerate -m "%~1"
if !errorlevel! equ 0 (
    echo %GREEN%Migration generated%NC%
    echo %YELLOW%Review the file in alembic/versions/ before applying!%NC%
) else (
    echo %RED%Failed to generate migration%NC%
)
echo.
exit /b !errorlevel!

:migrate_create
echo.
echo %BLUE%Creating empty migration: '%~1'%NC%
alembic revision -m "%~1"
echo %GREEN%Empty migration created%NC%
echo %YELLOW%Edit the file in alembic/versions/ to add upgrade/downgrade logic%NC%
echo.
exit /b !errorlevel!

:migrate_upgrade_head
echo.
echo %YELLOW%Applying all pending migrations...%NC%
echo %RED%WARNING: Ensure database is backed up!%NC%
set /p confirm="Continue? (y/n): "
if /i not "%confirm%"=="y" (
    echo Cancelled
    exit /b 1
)
alembic upgrade head
if !errorlevel! equ 0 (
    echo %GREEN%Migrations applied successfully%NC%
    call :migrate_current
) else (
    echo %RED%Migration failed%NC%
)
exit /b !errorlevel!

:migrate_upgrade_one
echo.
echo %YELLOW%Applying one migration...%NC%
alembic upgrade +1
if !errorlevel! equ 0 (
    echo %GREEN%Migration applied%NC%
    call :migrate_current
) else (
    echo %RED%Migration failed%NC%
)
exit /b !errorlevel!

:migrate_downgrade_one
echo.
echo %YELLOW%Rolling back one migration...%NC%
echo %RED%WARNING: This will revert the last migration!%NC%
set /p confirm="Continue? (y/n): "
if /i not "%confirm%"=="y" (
    echo Cancelled
    exit /b 1
)
alembic downgrade -1
if !errorlevel! equ 0 (
    echo %GREEN%Migration rolled back%NC%
    call :migrate_current
) else (
    echo %RED%Rollback failed%NC%
)
exit /b !errorlevel!

:migrate_downgrade_all
echo.
echo %RED%WARNING: This will rollback ALL migrations!%NC%
set /p confirm="Type 'I understand' to continue: "
if not "%confirm%"=="I understand" (
    echo Cancelled
    exit /b 1
)
alembic downgrade base
if !errorlevel! equ 0 (
    echo %GREEN%All migrations rolled back%NC%
) else (
    echo %RED%Rollback failed%NC%
)
exit /b !errorlevel!

:migrate_test
echo.
echo %BLUE%Testing migrations ^(no changes will be made^)...%NC%
alembic upgrade head --sql
echo.
exit /b !errorlevel!

:migrate_backup
echo.
echo %BLUE%Creating database backup...%NC%
REM Get timestamp
for /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c%%a%%b)
for /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a%%b)
set backup_file=backup_!mydate!_!mytime!.sql
pg_dump !DATABASE_URL! > !backup_file!
if !errorlevel! equ 0 (
    for %%A in (!backup_file!) do set size=%%~zA
    echo %GREEN%Backup created: !backup_file! ^(!size! bytes^)%NC%
) else (
    echo %RED%Backup failed%NC%
)
echo.
exit /b !errorlevel!

:migrate_check_prod
echo.
echo %BLUE%Production Migration Check%NC%
echo ─────────────────────────────────────────
echo %YELLOW%Current Version:%NC%
alembic current
echo.
echo %YELLOW%Latest Available:%NC%
alembic heads
echo ─────────────────────────────────────────
echo.
exit /b !errorlevel!

:migrate_health_check
echo.
echo %BLUE%Checking database connection...%NC%
python -c "
import os
from sqlalchemy import create_engine, text

url = os.getenv('DATABASE_URL')
try:
    engine = create_engine(url)
    with engine.connect() as conn:
        conn.execute(text('SELECT 1'))
    print('Database connection OK')
except Exception as e:
    print(f'Database connection failed: {e}')
    exit(1)
"
exit /b !errorlevel!
