#!/bin/bash

# Fover Backend - Database Migration Helper Scripts
# Usage: source migrate.sh && migrate_<command>

# Set colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if .env exists
if [ -f .env ]; then
    export $(cat .env | grep -v '#' | xargs)
fi

# Check if DATABASE_URL is set
check_database_url() {
    if [ -z "$DATABASE_URL" ]; then
        echo -e "${RED}✗ DATABASE_URL not set!${NC}"
        echo -e "${YELLOW}Set it with: export DATABASE_URL='postgresql://user:pass@host:5432/db'${NC}"
        return 1
    fi
    return 0
}

# Display help
migrate_help() {
    cat << 'EOF'
┌─────────────────────────────────────────────────┐
│   Fover Backend Migration Helper Scripts         │
└─────────────────────────────────────────────────┘

USAGE: source migrate.sh && migrate_<command>

AVAILABLE COMMANDS:

Development:
  migrate_status          - Show current migration version
  migrate_generate        - Generate autogenerated migration
  migrate_create          - Create empty migration (manual edit)
  migrate_upgrade_head    - Apply all pending migrations
  migrate_upgrade_one     - Apply one pending migration
  migrate_downgrade_one   - Rollback one migration
  migrate_downgrade_all   - Rollback all migrations
  migrate_history         - Show migration history
  migrate_current         - Show current version
  migrate_test            - Test migration without applying

Production:
  migrate_backup          - Backup database
  migrate_check_prod      - Check production migrations
  migrate_rollback_plan   - Show rollback plan

Utilities:
  migrate_help            - Show this help message
  migrate_health_check    - Check database connection

EXAMPLES:

  # Generate a new migration
  migrate_generate "add email verification"

  # Check status before deploying
  migrate_status

  # Safely upgrade one migration at a time
  migrate_upgrade_one
  migrate_upgrade_one
  migrate_upgrade_one

  # Backup then upgrade all
  migrate_backup && migrate_upgrade_head

  # Show what would be applied
  migrate_test

EOF
}

# Check database connection
migrate_health_check() {
    echo -e "${BLUE}Checking database connection...${NC}"
    check_database_url || return 1
    
    python3 -c "
import os
from sqlalchemy import create_engine, text

url = os.getenv('DATABASE_URL')
try:
    engine = create_engine(url)
    with engine.connect() as conn:
        conn.execute(text('SELECT 1'))
    print('\033[0;32m✓ Database connection OK\033[0m')
except Exception as e:
    print(f'\033[0;31m✗ Database connection failed: {e}\033[0m')
    exit(1)
" || return 1
}

# Show current status
migrate_status() {
    echo -e "${BLUE}Migration Status${NC}"
    check_database_url || return 1
    echo "─────────────────────────────────────────"
    alembic current
    echo "─────────────────────────────────────────"
    echo -e "${YELLOW}Latest available: $(alembic heads)${NC}"
}

# Show current version only
migrate_current() {
    check_database_url || return 1
    alembic current
}

# Show migration history
migrate_history() {
    echo -e "${BLUE}Migration History${NC}"
    check_database_url || return 1
    alembic history --verbose
}

# Generate new migration (autogenerate)
migrate_generate() {
    local message="${1:-update schema}"
    
    check_database_url || return 1
    
    echo -e "${BLUE}Generating migration: '${message}'${NC}"
    alembic revision --autogenerate -m "$message"
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Migration generated${NC}"
        echo -e "${YELLOW}Review the file in alembic/versions/ before applying!${NC}"
    else
        echo -e "${RED}✗ Failed to generate migration${NC}"
        return 1
    fi
}

# Create empty migration (manual)
migrate_create() {
    local message="${1:-manual migration}"
    
    check_database_url || return 1
    
    echo -e "${BLUE}Creating empty migration: '${message}'${NC}"
    alembic revision -m "$message"
    echo -e "${GREEN}✓ Empty migration created${NC}"
    echo -e "${YELLOW}Edit the file in alembic/versions/ to add upgrade/downgrade logic${NC}"
}

# Apply all pending migrations
migrate_upgrade_head() {
    check_database_url || return 1
    
    echo -e "${YELLOW}Applying all pending migrations...${NC}"
    echo -e "${RED}⚠ Ensure database is backed up!${NC}"
    read -p "Continue? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled"
        return 1
    fi
    
    alembic upgrade head
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Migrations applied successfully${NC}"
        migrate_current
    else
        echo -e "${RED}✗ Migration failed${NC}"
        return 1
    fi
}

# Apply one migration
migrate_upgrade_one() {
    check_database_url || return 1
    
    echo -e "${YELLOW}Applying one migration...${NC}"
    alembic upgrade +1
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Migration applied${NC}"
        migrate_current
    else
        echo -e "${RED}✗ Migration failed${NC}"
        return 1
    fi
}

# Rollback one migration
migrate_downgrade_one() {
    check_database_url || return 1
    
    echo -e "${YELLOW}Rolling back one migration...${NC}"
    echo -e "${RED}⚠ This will revert the last migration!${NC}"
    read -p "Continue? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled"
        return 1
    fi
    
    alembic downgrade -1
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Migration rolled back${NC}"
        migrate_current
    else
        echo -e "${RED}✗ Rollback failed${NC}"
        return 1
    fi
}

# Rollback all migrations
migrate_downgrade_all() {
    check_database_url || return 1
    
    echo -e "${RED}⚠⚠⚠ WARNING ⚠⚠⚠${NC}"
    echo "This will rollback ALL migrations and clear the schema!"
    read -p "Type 'I understand' to continue: " confirm
    
    if [ "$confirm" != "I understand" ]; then
        echo "Cancelled"
        return 1
    fi
    
    alembic downgrade base
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ All migrations rolled back${NC}"
    else
        echo -e "${RED}✗ Rollback failed${NC}"
        return 1
    fi
}

# Test what would be applied without applying
migrate_test() {
    check_database_url || return 1
    
    echo -e "${BLUE}Testing migrations (no changes will be made)...${NC}"
    alembic upgrade head --sql
}

# Backup database
migrate_backup() {
    check_database_url || return 1
    
    echo -e "${BLUE}Creating database backup...${NC}"
    
    # Extract database name from URL
    DB_NAME=$(echo $DATABASE_URL | rev | cut -d'/' -f1 | rev)
    BACKUP_FILE="backup_${DB_NAME}_$(date +%Y%m%d_%H%M%S).sql"
    
    pg_dump "$DATABASE_URL" > "$BACKUP_FILE"
    
    if [ $? -eq 0 ]; then
        SIZE=$(du -h "$BACKUP_FILE" | cut -f1)
        echo -e "${GREEN}✓ Backup created: ${BACKUP_FILE} (${SIZE})${NC}"
    else
        echo -e "${RED}✗ Backup failed${NC}"
        return 1
    fi
}

# Check production migrations
migrate_check_prod() {
    check_database_url || return 1
    
    echo -e "${BLUE}Production Migration Check${NC}"
    echo "─────────────────────────────────────────"
    echo -e "${YELLOW}Current Version:${NC}"
    alembic current
    echo ""
    echo -e "${YELLOW}Latest Available:${NC}"
    alembic heads
    echo ""
    echo -e "${YELLOW}Recent History:${NC}"
    alembic history --verbose -r 10
}

# Show rollback plan
migrate_rollback_plan() {
    echo -e "${BLUE}Rollback Plan${NC}"
    echo "─────────────────────────────────────────"
    echo -e "${YELLOW}To rollback the last migration:${NC}"
    echo "  alembic downgrade -1"
    echo ""
    echo -e "${YELLOW}To rollback all migrations:${NC}"
    echo "  alembic downgrade base"
    echo ""
    echo -e "${YELLOW}To rollback to specific version:${NC}"
    echo "  alembic downgrade <revision_id>"
}

# Default action
if [ "$1" = "" ]; then
    migrate_help
fi
