apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fover-backend-hpa
  namespace: fover-backend
  labels:
    app: fover-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fover-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
