apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fover-backend-ingress
  namespace: fover-backend
  labels:
    app: fover-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  rules:
    - host: fover.example.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: fover-backend-service
                port:
                  number: 80
