"""ensure local Match identity generates future keys

Revision ID: 20260910_match_identity_sequence
Revises: 20260910_separate_match_identity
"""

from alembic import op


revision = "20260910_match_identity_sequence"
down_revision = "20260910_separate_match_identity"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE matches ALTER COLUMN local_match_id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('matches', 'local_match_id'), "
        "COALESCE((SELECT MAX(local_match_id) FROM matches), 1), true)"
    )


def downgrade():
    op.execute("ALTER TABLE matches ALTER COLUMN local_match_id DROP IDENTITY IF EXISTS")